apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pvc-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  hostPath:
    path: /tmp/
    # path: /data/mongo