apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template: 
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - name: posts
        image: docker.io/ershubhamgupta1/posts:0.1.2
        imagePullPolicy: Always
        env:
          - name: elasticsearch_node
            value: https://elasticsearch-sample-es-http.default.svc.cluster.local:9200
          - name: elasticsearch_certificate
            valueFrom:
              secretKeyRef:
                name: elasticsearch-sample-es-http-certs-internal
                key: ca.crt
          - name: elasticsearch_password
            valueFrom:
              secretKeyRef:
                name: elasticsearch-sample-es-elastic-user
                key: elastic
        volumeMounts:
          - mountPath: /app/story
            name: story-volume
          # - mountPath: /app
          #   name: host-machine-volume
            
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc
        # - name: host-machine-volume
        #   hostPath:
        #     path: /Users/shubhamgupta/learning/k8-MERN-App/microservices/node-posts
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000