apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: docker.io/ershubhamgupta1/react-app:0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-clusterip-srv
spec:
  selector:
    app: react-app
  ports:
    - name: react-app
      protocol: TCP
      port: 6000
      targetPort: 3000