apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 8
  selector:
    matchLabels:
      app: auth
  template: 
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: ershubhamgupta1/auth:0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 5000
      targetPort: 5000